Alias /phpmyadmin "C:/Pirulug/PiruWamp/bin/phpmyadmin/_phpMyAdmin-6.0-snapshot/phpMyAdmin-6.0+snapshot-all-languages/"

# to give access from outside 
# replace the lines
#
# Require local
# 
# by
#
# Require all granted
#

<Directory "C:/Pirulug/PiruWamp/bin/phpmyadmin/_phpMyAdmin-6.0-snapshot/phpMyAdmin-6.0+snapshot-all-languages/">
	Options Indexes FollowSymLinks MultiViews
	AllowOverride all  
 
	Require all granted
 
</Directory>
