# Apache Versions Repository
_apache-2.4.67 = https://www.apachelounge.com/download/VS18/binaries/httpd-2.4.67-260309-Win64-VS18.zip
apache-2.4.62 = https://www.apachelounge.com/download/VS17/binaries/httpd-2.4.62-240904-win64-VS17.zip
apache-2.4.66 = https://www.apachelounge.com/download/VS18/binaries/httpd-2.4.66-260223-Win64-VS18.zip
