# PiruWamp Configuration
wamp_root = C:\Pirulug\PiruWamp
php_version = _php-8.5.6
apache_version = _apache-2.4.67
phpmyadmin_version = _phpMyAdmin-6.0-snapshot
mariadb_version = MariaDB-12.2.2
php_extensions = bz2,curl,fileinfo,gd,gettext,iconv,intl,mbstring,exif,mysqli,openssl,pdo_mysql,pdo_sqlite,zip,sodium
