# MariaDB Versions Repository
_mariadb-12.2.2 = https://mirror.insacom.cl/mariadb///mariadb-12.2.2/winx64-packages/mariadb-12.2.2-winx64.zip
MariaDB-12.2.2 = https://mirror.insacom.cl/mariadb///mariadb-12.2.2/winx64-packages/mariadb-12.2.2-winx64.zip
MariaDB-11.8.6 = https://mirror.insacom.cl/mariadb///mariadb-11.8.6/winx64-packages/mariadb-11.8.6-winx64.zip
