# phpMyAdmin Versions Repository
_phpMyAdmin-6.0-snapshot = https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0+snapshot-all-languages.zip
phpMyAdmin-latest = https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip
phpMyAdmin-5.2-snapshot = https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2+snapshot-all-languages.zip
phpMyAdmin-6.0-snapshot = https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0+snapshot-all-languages.zip
phpMyAdmin-5.2.3 = https://files.phpmyadmin.net/phpMyAdmin/5.2.3/phpMyAdmin-5.2.3-all-languages.zip
